Shade JLine and JAnsi
Ref coursier/coursier#1283

Starting 2.0.0-RC3-2, I am seeing following runtime error:

```
[info] [error] java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.AnsiOutputStream
[info] [error] 	at jline.internal.Ansi.stripAnsi(Ansi.java:28)
[info] [error] 	at jline.console.ConsoleReader.setPrompt(ConsoleReader.java:499)
[info] [error] 	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2425)
[info] [error] 	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
[info] [error] 	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
```

This is likely due to the conflict between JAnsi 1.18 and JAnsi 2.12 included into JLine 2 that sbt is using. This adds more shading to workaround this issue.